version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: expertnsk/foodgram_bckend:latest
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/
      - ../data/:/app/data/
    depends_on:
      - db
    env_file:
      - ./.env
    
    restart: always

  frontend:
    image: expertnsk/foodgram_frntend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/
      - ../data/:/var/html/data/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value: