# Generated by Django 3.2.15 on 2022-09-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Тег в рецепте', 'verbose_name_plural': 'Теги в рецептах'},
        ),
    ]
